version: 0.2

env:
  variables:
    TABLE_NAME: "TwitterAutomation"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - cd lambda
      - pip install -r requirements.txt -t .
      - cd ..
      - sam build -t template.yaml
  post_build:
    commands:
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket codepipeline-us-east-1-179093572111 --s3-prefix lambda
      - sam deploy --template-file packaged.yaml --stack-name tweet-posting-stack --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides \
          ParameterKey=Region,ParameterValue=$AWS_REGION \
          ParameterKey=AccountID,ParameterValue=$AWS_ACCOUNT_ID \
          ParameterKey=TwitterConsumerKey,ParameterValue=$TWITTER_CONSUMER_KEY \
          ParameterKey=TwitterConsumerSecret,ParameterValue=$TWITTER_CONSUMER_SECRET \
          ParameterKey=TwitterAccessToken,ParameterValue=$TWITTER_ACCESS_TOKEN \
          ParameterKey=TwitterAccessTokenSecret,ParameterValue=$TWITTER_ACCESS_TOKEN_SECRET

artifacts:
  files:
    - packaged.yaml